# Generated by Django 2.1.7 on 2019-04-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('regid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
