# Generated by Django 2.1.7 on 2019-04-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addcat',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('catnm', models.CharField(max_length=50)),
                ('caticon', models.CharField(max_length=100)),
            ],
        ),
    ]
