# Generated by Django 2.1.5 on 2019-04-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('txnid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=100)),
                ('adsid', models.CharField(max_length=100)),
                ('adsprice', models.CharField(max_length=100)),
                ('ptime', models.CharField(max_length=100)),
            ],
        ),
    ]
